version: "3.9"

services:
  amfa:
    build:
      context: ../
      dockerfile: docker/local.Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ../:/go
      - ../local_data/test:/test
    env_file:
      - ../src/.env

  amfa-db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ../local_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=amfa_user
      - POSTGRES_PASSWORD=amfa_password
      - POSTGRES_DB=amfa_db

  amfa-cache:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - ../local_data/redis:/redis
